from environs import Env

env = Env()
env.read_env()

LEXICON_API_WEB_ATLANT: dict[str, str] = {
    'ATLANT_API_URL': env.str('ATLANT_API_URL'),
    'ATLANT_API_ADD_COMPANY': env.str('ATLANT_API_ADD_COMPANY'),
    'ATLANT_API_ADD_USER': env.str('ATLANT_API_ADD_USER'),
    'ATLANT_API_UPDATE_USER': env.str('ATLANT_API_UPDATE_USER'),
    'ATLANT_API_DELETE_MANAGER': env.str('ATLANT_API_DELETE_MANAGER'),
    'ATLANT_API_DELETE_VIEWER': env.str('ATLANT_API_DELETE_VIEWER'),
    'ATLANT_API_ADD_PROJECT': env.str('ATLANT_API_ADD_PROJECT'),
    'ATLANT_API_UPDATE_PROJECT': env.str('ATLANT_API_UPDATE_PROJECT'),
    'ATLANT_API_SET_USER_TO_PROJECT': env.str('ATLANT_API_SET_USER_TO_PROJECT'),
    'ATLANT_API_REMOVE_USER_FROM_PROJECT': env.str('ATLANT_API_REMOVE_USER_FROM_PROJECT'),
    'ATLANT_API_DELETE_PROJECT': env.str('ATLANT_API_DELETE_PROJECT'),
    'ATLANT_API_LOGOUT_FROM_SESSIONS': env.str('ATLANT_API_LOGOUT_FROM_SESSIONS')
}

LEXICON_API_DATA: dict[str, str] = {
    'USER': env.str('ATLANT_API_LOGIN'),
    'PASSWORD': env.str('ATLANT_API_PASSWORD')
}

LEXICON_WEB_ATLANT_REPORTS: dict[str, str] = {
    'ADDRESS_REPORT': env.str('ATLANT_WEB_ADDRESS'),
    'PROJECT_REPORT': env.str('ATLANT_WEB_GET_PROJECT_REPORT'),
    'COMPANY_REPORT': env.str('ATLANT_WEB_GET_COMPANY_REPORT'),
    'LIST_REPORT': env.str('ATLANT_WEB_GET_COMPANY_REPORT')
}
