"""Baseline migration

Revision ID: f4a892f3f9e8
Revises: 53cf98b1456f
Create Date: 2024-11-07 13:52:58.975719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a892f3f9e8'
down_revision: Union[str, None] = '53cf98b1456f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """INSERT INTO roles (id, role) VALUES
          (1, 'admin'),
          (2, 'manager'), 
          (3, 'superadmin'), 
          (4, 'viewer')
          """)

    op.execute("""
                INSERT INTO connected_systems (system) VALUES 
                ('Yandex Direct'),
                ('Yandex Metrika');
            """)

    op.execute("""
                INSERT INTO companies (company) VALUES 
                ('Atlant');
            """)

    op.execute("""
                INSERT INTO users (id, full_name, company_id, role_id, login, password, active) VALUES 
                (gen_random_uuid(), 
                'Boss',
                 1, 
                 3, 
                 'bossorder', 
                 '$argon2id$v=19$m=65536,t=3,p=4$1nv2vfaHG8igEkxJ6uayWw$R7UOPzSgq0/VPG4KWjLz5GJGM1DXgnTMN5ub/bivfvQ', 
                 true);
            """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
