"""initial

Revision ID: 53cf98b1456f
Revises: 
Create Date: 2024-11-07 13:40:58.566018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '53cf98b1456f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('company', sa.String(length=150), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('company')
                    )

    op.create_table('connected_systems',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('system', sa.String(length=300), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('system')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('role', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('role')
                    )

    op.create_table('users',
                    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('tg_id', sa.BigInteger(), nullable=True),
                    sa.Column('full_name', sa.String(length=300), nullable=True),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.String(length=20), nullable=False),
                    sa.Column('password', sa.String(length=300), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text("(NOW() AT TIME ZONE 'UTC' + interval '7 hour')"), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login'),
                    sa.UniqueConstraint('tg_id')
                    )


    op.create_table('projects',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=500), nullable=False),
                    sa.Column('description', sa.String(length=4096), nullable=False),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('user_login', sa.String(length=120), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text("(NOW() AT TIME ZONE 'UTC' + interval '7 hour')"), nullable=False),
                    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_login'], ['users.login'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('project_user',
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('project_id', 'user_id')
                    )

    op.create_table('yandex_accesses',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('system_id', sa.Integer(), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('access_token', sa.String(length=300), nullable=False),
                    sa.Column('expires_in', sa.Integer(), nullable=False),
                    sa.Column('refresh_token', sa.String(length=400), nullable=False),
                    sa.Column('token_type', sa.String(length=300), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text("(NOW() AT TIME ZONE 'UTC' + interval '7 hour')"), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['system_id'], ['connected_systems.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('yandex_direct_logins',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('direct_login', sa.String(length=500), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text("(NOW() AT TIME ZONE 'UTC' + interval '7 hour')"), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('yandex_metrika_counters',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.Column('counter_name', sa.String(length=500), nullable=False),
                    sa.Column('counter_id', sa.BigInteger(), nullable=False),
                    sa.Column('attribution', sa.String(length=500), nullable=False),
                    sa.Column('minor_attribution', sa.String(length=500), nullable=True),
                    sa.Column('names_key_goals', sa.ARRAY(sa.String(length=1000)), nullable=False),
                    sa.Column('names_minor_goals', sa.ARRAY(sa.String(length=1000)), nullable=True),
                    sa.Column('key_goals', sa.ARRAY(sa.BigInteger()), nullable=False),
                    sa.Column('minor_goals', sa.ARRAY(sa.BigInteger()), nullable=True),
                    sa.Column('ecommerce', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text("(NOW() AT TIME ZONE 'UTC' + interval '7 hour')"), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yandex_metrika_counters')
    op.drop_table('yandex_direct_logins')
    op.drop_table('yandex_accesses')
    op.drop_table('project_user')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('connected_systems')
    op.drop_table('companies')
    # ### end Alembic commands ###
