"""Baseline migration

Revision ID: f4a892f3f9e8
Revises: 53cf98b1456f
Create Date: 2024-11-07 13:52:58.975719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a892f3f9e8'
down_revision: Union[str, None] = '53cf98b1456f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_viewer',
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('viewer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manager_id', 'viewer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager_viewer')
    # ### end Alembic commands ###
