"""added colum report to Companies

Revision ID: daaf67f2a9db
Revises: 5d77cf67b746
Create Date: 2025-07-11 15:10:41.083087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daaf67f2a9db'
down_revision: Union[str, None] = '5d77cf67b746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('report', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'report')
    # ### end Alembic commands ###
