"""viewer manager added

Revision ID: c3ef5d801b13
Revises: bb4f99d55939
Create Date: 2025-01-23 12:03:36.811794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ef5d801b13'
down_revision: Union[str, None] = 'bb4f99d55939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_viewer',
    sa.Column('manager_id', sa.Uuid(), nullable=False),
    sa.Column('viewer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manager_id', 'viewer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager_viewer')
    # ### end Alembic commands ###
